# AHE - Age & Gender

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

# Importing data that has filtered out Boruta features, on which training the classifier is required: 
train_df = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/Boruta_ahe/Boruta_data/boruta_train_summ.csv")
val_df  = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/Boruta_ahe/Boruta_data/boruta_val_summ.csv")
test_df = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/Boruta_ahe/Boruta_data/boruta_test_summ.csv")


# Joining the training and the validation set to create a single dataframe on 
# which training of the classifier would be done: 
final_train_data = pd.concat((train_df, val_df), axis=0)

In [2]:
import sklearn
sklearn.__version__

'0.21.2'

In [3]:
train_df.shape
val_df.shape

(1332, 446)

(392, 446)

In [4]:
X = train_df[train_df.columns.difference(['id', 'label'])]
# For label or target whatever you might wanna call it: 
Y = train_df.loc[:, train_df.columns == 'label']
X_train = X
y_train = Y

In [5]:
# Male - 0 and Female -1
X_train['GENDER'].replace(['M','F'],[0,1], inplace=True)

/anaconda3/envs/tav_lab/lib/python3.6/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [6]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=1750)

In [7]:
model.fit(X_train, y_train)

/anaconda3/envs/tav_lab/lib/python3.6/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1750,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [17]:
# For features: 
X_test = test_df[test_df.columns.difference(['id','label'])]
# For label or target whatever you might wanna call it: 
y_test = test_df.loc[:, test_df.columns == 'label'] 

In [22]:
X_test.iloc[:, 0].replace(['M','F'],[0,1], inplace=True)

In [16]:
y_proba = model.predict_proba(X_test)

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_auc_score

In [12]:
predicted = (y_proba[:,1] >= 0.59).astype('int')

accuracy = accuracy_score(y_test, predicted)

In [13]:
predicted

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,

In [14]:
accuracy
roc_auc_score(y_test, pd.DataFrame(y_proba)[1])

0.6938775510204082

0.7754689942678478

In [15]:
import pickle
filename = 'ahe_rf_age_gender.sav'
pickle.dump(model, open(filename, 'wb'))

# Shock - Age & Gender

In [26]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

# Importing data that has filtered out Boruta features, on which training the classifier is required: 
train_df = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/Shock_rf/Boruta_data/boruta_train_summ.csv")
val_df  = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/Shock_rf/Boruta_data/boruta_val_summ.csv")
test_df = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/Shock_rf/Boruta_data/boruta_test_summ.csv")


# Joining the training and the validation set to create a single dataframe on 
# which training of the classifier would be done: 
final_train_data = pd.concat((train_df, val_df), axis=0)

In [34]:
X = train_df[train_df.columns.difference(['id', 'label'])]
# For label or target whatever you might wanna call it: 
Y = train_df.loc[:, train_df.columns == 'label']
X_train = X
y_train = Y

In [37]:
# Male - 0 and Female -1
X_train['GENDER'].replace([0,1],[1,0], inplace=True)

/anaconda3/envs/tav_lab/lib/python3.6/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [42]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=1250)

In [43]:
model.fit(X_train, y_train)

/anaconda3/envs/tav_lab/lib/python3.6/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1250,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [46]:
# For features: 
X_test = test_df[test_df.columns.difference(['id','label'])]
# For label or target whatever you might wanna call it: 
y_test = test_df.loc[:, test_df.columns == 'label'] 

In [47]:
X_test["GENDER"].replace([1,0],[0,1], inplace=True)

/anaconda3/envs/tav_lab/lib/python3.6/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [48]:
y_proba = model.predict_proba(X_test)

In [49]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_auc_score

In [50]:
predicted = (y_proba[:,1] >= 0.61).astype('int')

accuracy = accuracy_score(y_test, predicted)

In [51]:
predicted

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,

In [52]:
accuracy
roc_auc_score(y_test, pd.DataFrame(y_proba)[1])

0.7518072289156627

0.8451559615197746

In [53]:
import pickle
filename = 'shock_rf_age_gender.sav'
pickle.dump(model, open(filename, 'wb'))

# LOS - Age & Gender

In [68]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np

# Importing data that has filtered out Boruta features, on which training the classifier is required: 
train_df = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/LOS/boruta_train_summ.csv")
val_df  = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/LOS/boruta_val_summ.csv")
test_df = pd.read_csv("/Users/prakritiailavadi/Desktop/post_grad/project2/LOS/boruta_test_summ.csv")


# Joining the training and the validation set to create a single dataframe on 
# which training of the classifier would be done: 
final_train_data = pd.concat((train_df, val_df), axis=0)

In [73]:
X = train_df[train_df.columns.difference(['id', 'LOS_disc'])]
# For label or target whatever you might wanna call it: 
Y = train_df.loc[:, train_df.columns == 'LOS_disc']
X_train = X
y_train = Y

In [74]:
# Male - 0 and Female -1
X_train['GENDER'].replace([0,1],[1,0], inplace=True)

In [75]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=1250)

In [76]:
X_train.shape
y_train.shape

(1430, 2746)

(1430, 1)

In [77]:
model.fit(X_train, y_train)

/anaconda3/envs/tav_lab/lib/python3.6/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1250,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [78]:
# For features: 
X_test = test_df[test_df.columns.difference(['id','LOS_disc'])]
# For label or target whatever you might wanna call it: 
y_test = test_df.loc[:, test_df.columns == 'LOS_disc'] 

X_test["GENDER"].replace([1,0],[0,1], inplace=True)

/anaconda3/envs/tav_lab/lib/python3.6/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [81]:
y_proba = model.predict_proba(X_test)

In [82]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_auc_score

In [83]:
predicted = (y_proba[:,1] >= 0.3264).astype('int')

accuracy = accuracy_score(y_test, predicted)

In [84]:
predicted

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [85]:
accuracy
roc_auc_score(y_test, pd.DataFrame(y_proba)[1])

0.7453416149068323

0.7787615046018407

In [86]:
import pickle
filename = 'los_rf_age_gender.sav'
pickle.dump(model, open(filename, 'wb'))