## App script

In [2]:
import pandas as pd
import numpy as np

In [11]:
pip install image

     |████████████████████████████████| 7.5MB 2.0MB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Note: you may need to restart the kernel to use updated packages.


In [27]:
import scipy as sp

In [32]:
import scipy.misc

In [22]:
from PIL import Image

In [25]:
pip install Keras

  Using cached https://files.pythonhosted.org/packages/f8/ba/2d058dcf1b85b9c212cc58264c98a4a7dd92c989b798823cc5690d062bb2/Keras-2.2.5-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
     |████████████████████████████████| 266kB 210kB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/03/21/1cdf7fa7868528b35c1a08a770eb9334279574a8b5f1d7a2966dcec14e42/h5py-2.9.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
  Stored in directory: /Users/prakritiailavadi/Library/Caches/pip/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030
Successfully built pyyaml
Note: you may need to restart the kernel to u

In [27]:
pip install tensorflow

     |████████████████████████████████| 105.8MB 104kB/s eta 0:00:01   |█▏                              | 3.9MB 4.1MB/s eta 0:00:26     |██████▏                         | 20.5MB 255kB/s eta 0:05:34     |████████▍                       | 27.9MB 298kB/s eta 0:04:22     |█████████▎                      | 30.6MB 277kB/s eta 0:04:32     |█████████████▋                  | 45.0MB 285kB/s eta 0:03:33     |███████████████▏                | 50.3MB 863kB/s eta 0:01:05     |███████████████████▋            | 64.7MB 1.2MB/s eta 0:00:34     |███████████████████████▊        | 78.5MB 626kB/s eta 0:00:44     |█████████████████████████▏      | 83.2MB 456kB/s eta 0:00:50
  Using cached https://files.pythonhosted.org/packages/d0/33/376510eb8d6246f3c30545f416b2263eee461e40940c2a4413c711bdf62d/google_pasta-0.1.7-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/7f/a1/cb18aa345c9d5272377f04be871f86b973d9db41937a3c558f4eb16ae924/grpcio-1.23.0-cp36-cp36m-macosx_10_9_x86_64.whl
  Using cache

In [3]:
import keras

Using TensorFlow backend.


In [4]:
filename = '/Users/prakritiailavadi/Desktop/post_grad/project2/shock App/p000020_264490_Abnormal_1_41_1201.csv'

In [5]:
cols = ['X.HR.','X.RESP.','X.SpO2.','final_abp_sys','final_abp_dias']

In [6]:
data = pd.read_csv(filename)

In [7]:
hr = np.array(data[[cols[0]]]).reshape(-1,256)
rr = np.array(data[[cols[1]]]).reshape(-1,256)
spo = np.array(data[[cols[2]]]).reshape(-1,256)
sys = np.array(data[[cols[3]]]).reshape(-1,256)
dia = np.array(data[[cols[4]]]).reshape(-1,256)

In [40]:
hr

array([[80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 79.9, 80. , 80. ,
        80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 80. , 79.2, 78.9, 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 80. , 80. , 79.8, 80. , 80. , 80. , 80. , 80. ,
        80.1, 80. , 80. , 80. , 77.4, 80.2, 77.4, 77.1, 74.8, 78.9, 79.9,
        80. , 80. , 80. , 80. , 80. , 80. , 79.9, 80. , 80. , 79.9, 80. ,
        80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80. , 79.9, 80. , 80.5, 80. , 80. , 80. , 80. , 80. ,
        80. , 80. , 80.7, 80.3, 80. , 

## Snake

In [8]:
X_dia_snake = np.zeros((dia.shape[0], 256), dtype = np.float32)
X_hr_snake = np.zeros((hr.shape[0], 256), dtype = np.float32)
X_rr_snake = np.zeros((rr.shape[0], 256), dtype = np.float32)
X_spo_snake = np.zeros((spo.shape[0], 256), dtype = np.float32)
X_sys_snake = np.zeros((sys.shape[0], 256), dtype = np.float32)

In [13]:
X_hr_snake

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [9]:
for i in range(dia.shape[0]):
    b=dia[i]
    k=0
    print('on audio {}'.format(i))
    for j in range(0,dia.shape[1],16):
        if k%2==0:
            X_dia_snake[i][j:j+16]=b[j:j+16]
        else:
            X_dia_snake[i][j:j+16]=np.flip(b[j:j+16],0)
        k+=1

on audio 0


In [10]:
for i in range(hr.shape[0]):
    b=hr[i]
    k=0
    print('on audio {}'.format(i))
    for j in range(0,hr.shape[1],16):
        if k%2==0:
            X_hr_snake[i][j:j+16]=b[j:j+16]
        else:
            X_hr_snake[i][j:j+16]=np.flip(b[j:j+16],0)
        k+=1

on audio 0


In [11]:
for i in range(rr.shape[0]):
    b=rr[i]
    k=0
    print('on audio {}'.format(i))
    for j in range(0,rr.shape[1],16):
        if k%2==0:
            X_rr_snake[i][j:j+16]=b[j:j+16]
        else:
            X_rr_snake[i][j:j+16]=np.flip(b[j:j+16],0)
        k+=1

on audio 0


In [12]:
for i in range(spo.shape[0]):
    b=spo[i]
    k=0
    print('on audio {}'.format(i))
    for j in range(0,spo.shape[1],16):
        if k%2==0:
            X_spo_snake[i][j:j+16]=b[j:j+16]
        else:
            X_spo_snake[i][j:j+16]=np.flip(b[j:j+16],0)
        k+=1

on audio 0


In [13]:
for i in range(sys.shape[0]):
    b=sys[i]
    k=0
    print('on audio {}'.format(i))
    for j in range(0,sys.shape[1],16):
        if k%2==0:
            X_sys_snake[i][j:j+16]=b[j:j+16]
        else:
            X_sys_snake[i][j:j+16]=np.flip(b[j:j+16],0)
        k+=1

on audio 0


In [14]:
X_sys_snake

array([[143.     , 142.3    , 145.6    , 144.9    , 141.9    , 146.4    ,
        143.9    , 150.3    , 126.6    , 138.5    , 138.7    , 140.1    ,
        146.6    , 145.5    , 147.8    , 148.1    , 144.5    , 143.1    ,
        141.7    , 139.8    , 137.5    , 136.9    , 146.6    , 151.     ,
        150.5    , 149.6    , 146.1    , 141.1    , 136.1    , 142.2    ,
        144.1    , 137.2    , 144.2    , 146.3    , 142.2    , 142.8    ,
        143.1    , 144.6    , 141.8    , 142.2    , 143.     , 141.4    ,
        141.1    , 138.7    , 145.7    , 145.2    , 143.3    , 142.8    ,
        138.4    , 134.8    , 138.2    , 139.4    , 138.     , 138.2    ,
        135.5    , 141.     , 139.8    , 138.7    , 139.9    , 134.9    ,
        139.9    , 137.8    , 138.8    , 138.2    , 142.8    , 141.3    ,
        144.2    , 144.3    , 144.3    , 140.2    , 143.3    , 145.7    ,
        144.8    , 144.8    , 148.     , 151.6    , 152.     , 152.5    ,
        154.4    , 149.2    , 151.5   

## Densenet Model prep

In [15]:
X = np.dstack([X_dia_snake, X_hr_snake, X_rr_snake, X_spo_snake, X_sys_snake])

In [16]:
X = X.reshape(-1,16,16,5)

In [17]:
X

array([[[[ 54.8,  80. ,  16.1,  96. , 143. ],
         [ 54.1,  80. ,   7.5,  95.8, 142.3],
         [ 55.9,  80. ,  13.3,  96. , 145.6],
         ...,
         [ 56.6,  80. ,  18.6,  96. , 145.5],
         [ 57.7,  80. ,  18.6,  96. , 147.8],
         [ 57.9,  80. ,  17.5,  96. , 148.1]],

        [[ 55.2,  80. ,  17.8,  96. , 144.5],
         [ 54.7,  80. ,  17.5,  96. , 143.1],
         [ 54.7,  80. ,  17.9,  96. , 141.7],
         ...,
         [ 54.7,  80. ,  16.5,  96.1, 142.2],
         [ 55.6,  80. ,  17. ,  96.4, 144.1],
         [ 53.9,  80. ,  16.8,  95.5, 137.2]],

        [[ 55.2,  80. ,  19.1,  96. , 144.2],
         [ 55.6,  80. ,  18.3,  96. , 146.3],
         [ 55.1,  80. ,  20.6,  95.9, 142.2],
         ...,
         [ 55.1,  80. ,  16.5,  96. , 145.2],
         [ 54.4,  80. ,  17.2,  96. , 143.3],
         [ 54.1,  80. ,  16.2,  96. , 142.8]],

        ...,

        [[ 50.2,  80. ,  12.9,  97. , 131.5],
         [ 49.8,  80. ,  13.1,  97. , 130.1],
         [ 48.8,  

In [30]:
array_resized_image = scipy.misc.imresize(X, (320, 240), interp='nearest', mode=None)

AttributeError: module 'scipy.misc' has no attribute 'imresize'

In [23]:
image = Image.fromarray(X, 'RGB')

ValueError: Too many dimensions: 4 > 3.

## Padding

In [78]:
X = np.pad(X, ((0,0), (7,7), (7,7), (0,0)), mode='constant')
print(X.shape)

(1, 30, 30, 5)


In [59]:
X

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        ...,

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         

In [79]:
img_height = 30
img_width = 30

In [80]:
mean_calc1 = np.load('mean_shock_image_mimic.npy')
std_calc1 = np.load('std_shock_image_mimic.npy')

In [62]:
import keras

In [81]:
from keras import backend as K
X -= mean_calc1
# Apply featurewise_std_normalization to test-data with statistics from train data
X /= (std_calc1 + K.epsilon())

In [64]:
X

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        ...,

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         

In [31]:
import os
import warnings

from keras import layers
from keras import models
from keras import backend

def dense_block(x, blocks, name):
    """A dense block.
    # Arguments
        x: input tensor.
        blocks: integer, the number of building blocks.
        name: string, block label.
    # Returns
        output tensor for the block.
    """
    for i in range(blocks):
        x = conv_block(x, 32, name=name + '_block' + str(i + 1))
    return x


def transition_block(x, reduction, name):
    """A transition block.
    # Arguments
        x: input tensor.
        reduction: float, compression rate at transition layers.
        name: string, block label.
    # Returns
        output tensor for the block.
    """
    bn_axis = 3 if backend.image_data_format() == 'channels_last' else 1
    x = layers.BatchNormalization(axis=bn_axis, epsilon=1.001e-5,
                                  name=name + '_bn')(x)
    x = layers.Activation('relu', name=name + '_relu')(x)
    x = layers.Conv2D(int(backend.int_shape(x)[bn_axis] * reduction), 1,
                      use_bias=False,
                      name=name + '_conv')(x)
    x = layers.AveragePooling2D(2, strides=2, name=name + '_pool')(x)
    return x


def conv_block(x, growth_rate, name):
    """A building block for a dense block.
    # Arguments
        x: input tensor.
        growth_rate: float, growth rate at dense layers.
        name: string, block label.
    # Returns
        Output tensor for the block.
    """
    bn_axis = 3 if backend.image_data_format() == 'channels_last' else 1
    x1 = layers.BatchNormalization(axis=bn_axis,
                                   epsilon=1.001e-5,
                                   name=name + '_0_bn')(x)
    x1 = layers.Activation('relu', name=name + '_0_relu')(x1)
    x1 = layers.Conv2D(4 * growth_rate, 1,
                       use_bias=False,
                       name=name + '_1_conv')(x1)
    x1 = layers.BatchNormalization(axis=bn_axis, epsilon=1.001e-5,
                                   name=name + '_1_bn')(x1)
    x1 = layers.Activation('relu', name=name + '_1_relu')(x1)
    x1 = layers.Conv2D(growth_rate, 3,
                       padding='same',
                       use_bias=False,
                       name=name + '_2_conv')(x1)
    x = layers.Concatenate(axis=bn_axis, name=name + '_concat')([x, x1])
    return x

def DenseNet(blocks=[6, 12, 24, 16]):
    
    input_shape = [img_height, img_width, 5]
    img_input = layers.Input(shape=input_shape)
    
    bn_axis = 3 if backend.image_data_format() == 'channels_last' else 1

    x = layers.ZeroPadding2D(padding=((3, 3), (3, 3)))(img_input)
    x = layers.Conv2D(64, 7, strides=2, use_bias=False, name='conv1/conv')(x)
    x = layers.BatchNormalization(
        axis=bn_axis, epsilon=1.001e-5, name='conv1/bn')(x)
    x = layers.Activation('relu', name='conv1/relu')(x)
    x = layers.ZeroPadding2D(padding=((1, 1), (1, 1)))(x)
    x = layers.MaxPooling2D(3, strides=2, name='pool1')(x)

    x = dense_block(x, blocks[0], name='conv2')
    x = transition_block(x, 0.5, name='pool2')
    x = dense_block(x, blocks[1], name='conv3')
    x = transition_block(x, 0.5, name='pool3')
    x = dense_block(x, blocks[2], name='conv4')
    x = transition_block(x, 0.5, name='pool4')
    x = dense_block(x, blocks[3], name='conv5')

    x = layers.BatchNormalization(
        axis=bn_axis, epsilon=1.001e-5, name='bn')(x)
    x = layers.Activation('relu', name='relu')(x)

    x = layers.GlobalAveragePooling2D(name='avg_pool')(x)
    x = layers.Dense(1, activation='sigmoid', name='fc')(x)

    # Ensure that the model takes into account
    # any potential predecessors of `input_tensor`.
    inputs = img_input
    model = models.Model(inputs, x, name='densenet121')
    return model


In [82]:
model = DenseNet()
adam = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
model.compile(loss='binary_crossentropy', optimizer=adam, metrics=['accuracy'])
model.load_weights('/Users/prakritiailavadi/Desktop/post_grad/project2/shock App/weights-snake-loop-model_0.hdf5')

In [86]:
result = model.predict(X)

In [84]:
result[0][0]

0.41117668

In [85]:
import pickle
filename = 'densenet.sav'
pickle.dump(model, open(filename, 'wb'))

In [ ]:
model.save()

In [88]:
import tensorflow as tf

In [89]:
tf.__version__

'1.14.0'

In [90]:
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.5.0-cp35-cp35m-win_amd64.whl

ERROR: tensorflow_gpu-1.5.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
Note: you may need to restart the kernel to use updated packages.
